export const colours = {
  blue: '#53B0BE',
  transBlue: '#53B0BECC',
  blueLight: '#D4EBEF',
  blueSuperLight: '#EEF7F8',
  yellow: '#FEDA41',
  transYellow: '#FEDA41CC',
  yellowLight: '#FFF8D9',
  yellowSuperLight: '#FFFBEC',
  green: '#A4BC39',
  transGreen: '#A4BC39CC',
  greenLight: '#E8EECD',
  greenSuperLight: '#F6F8EB',
  aqua: '#39BC85',
  transAqua: '#39BC85CC',
  aquaLight: '#CDEEE0',
  aquaSuperLight: '#EBF8F2',
  orange: '#F26B3C',
  transOrange: '#F26B3CCC',
  orangeLight: '#FCDACE',
  orangeSuperLight: '#FEF0EB',
  grey: '#818E99',
  transGrey: '#818E9933',
  darkGrey: '#1C3D43',
  textGrey: '#C9C9C9',
  red: '#f23c3c',
  redLight: '#fccece',
  redSuperLight: '#feebeb',
  purple: '#8153be',
  purpleLight: '#dfd4ef',
  purpleSuperLight: '#f2eef8'


}
